// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salon.Data;

#nullable disable

namespace Salon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("Name").HasColumnType("nvarchar(450)");
                    b.Property<string>("Value").HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Salon.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<int>("AccessFailedCount").HasColumnType("int");
                    b.Property<string>("AvatarUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int?>("LinkedEmployeeId").HasColumnType("int");
                    b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                    b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                    b.Property<string>("UserDepartment").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Salon.Models.AuditLog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("UserName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Module").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<int?>("EntityId").HasColumnType("int");
                    b.Property<string>("IpAddress").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Salon.Models.Appointment", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("AppointmentDate").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("CustomerId").HasColumnType("int");
                    b.Property<int?>("EmployeeId").HasColumnType("int");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.HasIndex("EmployeeId");
                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Salon.Models.AppointmentService", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AppointmentId").HasColumnType("int");
                    b.Property<int>("ServiceId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("AppointmentId");
                    b.HasIndex("ServiceId");
                    b.ToTable("AppointmentServices");
                });

            modelBuilder.Entity("Salon.Models.Attendance", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("AttendanceDate").HasColumnType("datetime2");
                    b.Property<TimeSpan?>("CheckIn").HasColumnType("time");
                    b.Property<TimeSpan?>("CheckOut").HasColumnType("time");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Salon.Models.Customer", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime?>("BirthDate").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").HasColumnType("nvarchar(max)");
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Gender").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Salon.Models.Department", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Salon.Models.Employee", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("BasicSalary").HasColumnType("decimal(18,3)").HasColumnName("BasicSalary");
                    b.Property<decimal>("Commission").HasColumnType("decimal(18,3)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Department").HasColumnType("nvarchar(max)");
                    b.Property<int?>("DepartmentId").HasColumnType("int");
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("HireDate").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("JobTitle").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Nationality").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Phone").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ResidencyExpiry").HasColumnType("datetime2");
                    b.Property<int>("ServiceType").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("DepartmentId");
                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Salon.Models.EmployeeAdvance", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("AdvanceDate").HasColumnType("datetime2");
                    b.Property<decimal>("Amount").HasColumnType("decimal(18,3)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<decimal>("DeductedAmount").HasColumnType("decimal(18,3)");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("PaidDate").HasColumnType("datetime2");
                    b.Property<string>("Reason").HasColumnType("nvarchar(max)");
                    b.Property<string>("PaymentMethod").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.ToTable("EmployeeAdvances");
                });

            modelBuilder.Entity("Salon.Models.Expense", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Amount").HasColumnType("decimal(18,3)");
                    b.Property<string>("Category").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("ExpenseDate").HasColumnType("datetime2");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("PaymentMethod").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Salon.Models.Message", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Body").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsBroadcast").HasColumnType("bit");
                    b.Property<bool>("IsRead").HasColumnType("bit");
                    b.Property<string>("ReceiverId").HasColumnType("nvarchar(max)");
                    b.Property<string>("SenderId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("SentAt").HasColumnType("datetime2");
                    b.Property<string>("Subject").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Salon.Models.Product", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Barcode").HasColumnType("nvarchar(max)");
                    b.Property<string>("Category").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("ExpiryDate").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int>("MinStockLevel").HasColumnType("int");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<decimal>("PurchasePrice").HasColumnType("decimal(18,3)");
                    b.Property<decimal>("SalePrice").HasColumnType("decimal(18,3)");
                    b.Property<int>("StockQuantity").HasColumnType("int");
                    b.Property<string>("Unit").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Products");
                });

            modelBuilder.Entity("Salon.Models.Salary", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("AdvanceDeducted").HasColumnType("decimal(18,3)");
                    b.Property<decimal>("Allowances").HasColumnType("decimal(18,3)");
                    b.Property<decimal>("BasicSalary").HasColumnType("decimal(18,3)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<decimal>("Deductions").HasColumnType("decimal(18,3)");
                    b.Property<int>("EmployeeId").HasColumnType("int");
                    b.Property<int>("Month").HasColumnType("int");
                    b.Property<decimal>("NetSalary").HasColumnType("decimal(18,3)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("PaidDate").HasColumnType("datetime2");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Year").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("EmployeeId");
                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("Salon.Models.Sale", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int?>("CustomerId").HasColumnType("int");
                    b.Property<decimal>("Discount").HasColumnType("decimal(18,3)");
                    b.Property<int?>("EmployeeId").HasColumnType("int");
                    b.Property<string>("InvoiceNumber").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("NetAmount").HasColumnType("decimal(18,3)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("PaymentMethod").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("SaleDate").HasColumnType("datetime2");
                    b.Property<string>("SaleType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,3)");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.HasIndex("EmployeeId");
                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Salon.Models.SaleItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ItemName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,3)");
                    b.Property<int?>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.Property<int>("SaleId").HasColumnType("int");
                    b.Property<int?>("ServiceId").HasColumnType("int");
                    b.Property<decimal>("Total").HasColumnType("decimal(18,3)");
                    b.HasKey("Id");
                    b.HasIndex("ProductId");
                    b.HasIndex("SaleId");
                    b.HasIndex("ServiceId");
                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("Salon.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Department").HasColumnType("nvarchar(max)");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<string>("Icon").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Salon.Models.Service", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").HasColumnType("nvarchar(max)");
                    b.Property<int?>("DurationMinutes").HasColumnType("int");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,3)");
                    b.Property<int?>("ServiceCategoryId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ServiceCategoryId");
                    b.ToTable("Services");
                });

            modelBuilder.Entity("Salon.Models.Shift", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("CashierName").HasColumnType("nvarchar(max)");
                    b.Property<decimal?>("ClosingBalance").HasColumnType("decimal(18,3)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<TimeSpan?>("EndTime").HasColumnType("time");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<decimal>("OpeningBalance").HasColumnType("decimal(18,3)");
                    b.Property<DateTime>("ShiftDate").HasColumnType("datetime2");
                    b.Property<TimeSpan>("StartTime").HasColumnType("time");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Salon.Models.StockMovement", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("MovementDate").HasColumnType("datetime2");
                    b.Property<string>("MovementType").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<int>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.Property<int>("QuantityAfter").HasColumnType("int");
                    b.Property<int>("QuantityBefore").HasColumnType("int");
                    b.Property<string>("Reason").HasColumnType("nvarchar(max)");
                    b.Property<string>("Reference").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("ProductId");
                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Salon.Models.Supplier", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Address").HasColumnType("nvarchar(max)");
                    b.Property<string>("ContactPerson").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                    b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Salon.Models.UserPermission", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("CanAccess").HasColumnType("bit");
                    b.Property<string>("Module").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("UserPermissions");
                });

            // Relationships
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                { b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                { b.HasOne("Salon.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                { b.HasOne("Salon.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Salon.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                { b.HasOne("Salon.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); });

            modelBuilder.Entity("Salon.Models.Appointment", b =>
                {
                    b.HasOne("Salon.Models.Customer", "Customer").WithMany("Appointments").HasForeignKey("CustomerId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Salon.Models.Employee", "Employee").WithMany().HasForeignKey("EmployeeId");
                    b.Navigation("Customer"); b.Navigation("Employee");
                });

            modelBuilder.Entity("Salon.Models.AppointmentService", b =>
                {
                    b.HasOne("Salon.Models.Appointment", "Appointment").WithMany("AppointmentServices").HasForeignKey("AppointmentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Salon.Models.Service", "Service").WithMany("AppointmentServices").HasForeignKey("ServiceId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Appointment"); b.Navigation("Service");
                });

            modelBuilder.Entity("Salon.Models.Attendance", b =>
                {
                    b.HasOne("Salon.Models.Employee", "Employee").WithMany("Attendances").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Salon.Models.Employee", b =>
                {
                    b.HasOne("Salon.Models.Department", "DepartmentRef").WithMany("Employees").HasForeignKey("DepartmentId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("DepartmentRef");
                });

            modelBuilder.Entity("Salon.Models.EmployeeAdvance", b =>
                {
                    b.HasOne("Salon.Models.Employee", "Employee").WithMany("Advances").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Salon.Models.Salary", b =>
                {
                    b.HasOne("Salon.Models.Employee", "Employee").WithMany("Salaries").HasForeignKey("EmployeeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Salon.Models.Sale", b =>
                {
                    b.HasOne("Salon.Models.Customer", "Customer").WithMany("Sales").HasForeignKey("CustomerId");
                    b.HasOne("Salon.Models.Employee", "Employee").WithMany().HasForeignKey("EmployeeId");
                    b.Navigation("Customer"); b.Navigation("Employee");
                });

            modelBuilder.Entity("Salon.Models.SaleItem", b =>
                {
                    b.HasOne("Salon.Models.Product", "Product").WithMany("SaleItems").HasForeignKey("ProductId");
                    b.HasOne("Salon.Models.Sale", "Sale").WithMany("SaleItems").HasForeignKey("SaleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Salon.Models.Service", "Service").WithMany("SaleItems").HasForeignKey("ServiceId");
                    b.Navigation("Product"); b.Navigation("Sale"); b.Navigation("Service");
                });

            modelBuilder.Entity("Salon.Models.Service", b =>
                {
                    b.HasOne("Salon.Models.ServiceCategory", "ServiceCategory").WithMany("Services").HasForeignKey("ServiceCategoryId");
                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Salon.Models.StockMovement", b =>
                {
                    b.HasOne("Salon.Models.Product", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Salon.Models.UserPermission", b =>
                {
                    b.HasOne("Salon.Models.ApplicationUser", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            // Navigations
            modelBuilder.Entity("Salon.Models.Appointment", b => { b.Navigation("AppointmentServices"); });
            modelBuilder.Entity("Salon.Models.Customer", b => { b.Navigation("Appointments"); b.Navigation("Sales"); });
            modelBuilder.Entity("Salon.Models.Department", b => { b.Navigation("Employees"); });
            modelBuilder.Entity("Salon.Models.Employee", b => { b.Navigation("Advances"); b.Navigation("Attendances"); b.Navigation("Salaries"); });
            modelBuilder.Entity("Salon.Models.Product", b => { b.Navigation("SaleItems"); });
            modelBuilder.Entity("Salon.Models.Sale", b => { b.Navigation("SaleItems"); });
            modelBuilder.Entity("Salon.Models.Service", b => { b.Navigation("AppointmentServices"); b.Navigation("SaleItems"); });
            modelBuilder.Entity("Salon.Models.ServiceCategory", b => { b.Navigation("Services"); });
#pragma warning restore 612, 618
        }
    }
}
